# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\render\resource\ui\HomeInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeInterface(object):
    def setupUi(self, HomeInterface):
        HomeInterface.setObjectName("HomeInterface")
        HomeInterface.resize(1500, 900)
        self.gridLayout = QtWidgets.QGridLayout(HomeInterface)
        self.gridLayout.setObjectName("gridLayout")
        self.SimulationWidget = CardWidget(HomeInterface)
        self.SimulationWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SimulationWidget.sizePolicy().hasHeightForWidth())
        self.SimulationWidget.setSizePolicy(sizePolicy)
        self.SimulationWidget.setMinimumSize(QtCore.QSize(500, 500))
        self.SimulationWidget.setMaximumSize(QtCore.QSize(800, 800))
        self.SimulationWidget.setObjectName("SimulationWidget")
        self.gridLayout.addWidget(self.SimulationWidget, 0, 0, 1, 1)
        self.CommandWidget = CardWidget(HomeInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CommandWidget.sizePolicy().hasHeightForWidth())
        self.CommandWidget.setSizePolicy(sizePolicy)
        self.CommandWidget.setMinimumSize(QtCore.QSize(325, 400))
        self.CommandWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CommandWidget.setObjectName("CommandWidget")
        self.gridLayout.addWidget(self.CommandWidget, 0, 3, 1, 1)
        self.TaskInfoWidget = CardWidget(HomeInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaskInfoWidget.sizePolicy().hasHeightForWidth())
        self.TaskInfoWidget.setSizePolicy(sizePolicy)
        self.TaskInfoWidget.setMinimumSize(QtCore.QSize(600, 500))
        self.TaskInfoWidget.setMaximumSize(QtCore.QSize(960, 800))
        self.TaskInfoWidget.setObjectName("TaskInfoWidget")
        self.gridLayout.addWidget(self.TaskInfoWidget, 0, 2, 1, 1)
        self.AgentInfoWidget = CardWidget(HomeInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AgentInfoWidget.sizePolicy().hasHeightForWidth())
        self.AgentInfoWidget.setSizePolicy(sizePolicy)
        self.AgentInfoWidget.setMinimumSize(QtCore.QSize(500, 310))
        self.AgentInfoWidget.setObjectName("AgentInfoWidget")
        self.gridLayout.addWidget(self.AgentInfoWidget, 1, 0, 1, 6)

        self.retranslateUi(HomeInterface)
        QtCore.QMetaObject.connectSlotsByName(HomeInterface)

    def retranslateUi(self, HomeInterface):
        _translate = QtCore.QCoreApplication.translate
        HomeInterface.setWindowTitle(_translate("HomeInterface", "Form"))
from qfluentwidgets import CardWidget
